version: '3.9'

services:
  web:
    image: saikat55mukherjee/react_django_app:latest
    ports:
      - "8001:8001"
  db:
    image: "mysql:latest"
    ports:
       - "3306:3307:3306"
     environment:
       - "MYSQL_ROOT_PASSWORD=test@123"
